// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBan-__H1pvbW3XXsBuqmFk9wByIS4V-74',
    appId: '1:57932921302:web:2ada5a01f34e1971320c77',
    messagingSenderId: '57932921302',
    projectId: 'to-do-71829',
    authDomain: 'to-do-71829.firebaseapp.com',
    storageBucket: 'to-do-71829.appspot.com',
    measurementId: 'G-WWGTGYCYWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq2X0MbIQixXLPVRuoNqk-CA3H2o-_aD4',
    appId: '1:57932921302:android:89c99af83db06f97320c77',
    messagingSenderId: '57932921302',
    projectId: 'to-do-71829',
    storageBucket: 'to-do-71829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy0j5pGCblUsxidtC96jU5Pqdtw-ZOjHk',
    appId: '1:57932921302:ios:8064435e120085af320c77',
    messagingSenderId: '57932921302',
    projectId: 'to-do-71829',
    storageBucket: 'to-do-71829.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy0j5pGCblUsxidtC96jU5Pqdtw-ZOjHk',
    appId: '1:57932921302:ios:8064435e120085af320c77',
    messagingSenderId: '57932921302',
    projectId: 'to-do-71829',
    storageBucket: 'to-do-71829.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBan-__H1pvbW3XXsBuqmFk9wByIS4V-74',
    appId: '1:57932921302:web:166be84c5ee2b0ce320c77',
    messagingSenderId: '57932921302',
    projectId: 'to-do-71829',
    authDomain: 'to-do-71829.firebaseapp.com',
    storageBucket: 'to-do-71829.appspot.com',
    measurementId: 'G-577M2JFSDN',
  );
}
